### ISSUE TITLE
qed crashes when trying to connect to small ISCE2 files of unusual type

### ISSUE THREAD

**Issue by EJFielding** [aivazis/qed#61]
The ionospheric correction code in ISCE2 `alosStack` workflow and `alos2App.py` creates several extra file types in the processing, including ".ion", ".win", and ".std" files. These are all single-band images and typically have very small sizes `<VRTDataset rasterXSize="319" rasterYSize="309">`. They include the ISCE2 ".vrt" and ".xml" files. When I try to connect to any of these files, either as `isce2` or `native` file type, the qed server crashes. I attach an example ".ion" file with its associated metadata files in a zip archive.

[filt_ion_80rlks_448alks-ion.zip](https://github.com/aivazis/qed/files/14843973/filt_ion_80rlks_448alks-ion.zip)

**Comment by aivazis** [comment]
The upcoming release of `qed` will be able to read these files using the `native` reader. Here is the `qed.yaml` file that lets me load the above file:

``` yaml
datasets:
    - "native.flat#ion"

ion:
    uri: "filt_ion_80rlks_448alks.ion"
    cell: float32
    shape: [309, 319]
```

Since most of the information necessary is available in the auxiliary XML file, I think it makes sense to create a specialized reader for all `float` isce2 datasets. Do you mind dropping here as complete a list of file extensions as possible for the `isce2` intermediate products that are similar in structure? Do you have any ideas about a good name for the "flat float" reader?

The release should be ready by Monday (2024/04/15). Do you want to try the code ahead of the release?
